### ISSUE TITLE
text/plane is not right

### ISSUE THREAD

**Issue by MikeyMoMo** [easytarget/esp32-cjmcu-531-demo#18]
It is text/plain

Maybe that's part of your problem.

**Comment by easytarget** [comment]
¿Que?
What problem?

**Comment by easytarget** [comment]
I'm guessing this was a mis-typing or other weirdness, since: 
```
[owen@hobbes esp32-cjmcu-531-demo]$ grep -ir 'plane' *
[owen@hobbes esp32-cjmcu-531-demo]$ 
```

**Comment by MikeyMoMo** [comment]
It is "plain", not "plane".  That's the problem.

**Comment by easytarget** [comment]
Nope, the problem is that the word 'plane' does not appear anywhere within my code and I don't know what you are talking about.
Maybe you are using somebody else's fork? or are otherwise confused.
